#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx

if ! ps aux | grep -q '[n]ginx'; then
    sudo /etc/init.d/nginx start
fi
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo /etc/init.d/nginx restart
