#!/bin/bash

# Create a backup of the original Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Use sed to replace a line with multiple lines in the Nginx configuration file
sed -i '/location \/ {/a \\tlocation \/redirect_me {\\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
/etc/init.d/nginx restart

