#!/usr/bin/env bash
# Create a backup of the original Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world!" | sudo tee /var/www/html/index
# Use sed to replace a line with multiple lines in the Nginx configuration file
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
# Restart Nginx to apply the changes
/etc/init.d/nginx restart

