#!/usr/bin/env bash
# Create a backup of the original Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Use sed to modify the Nginx configuration file to include custom error page for 404
sed -i '"46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
/etc/init.d/nginx restart

