#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx

sudo sed -i '/server {/a \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo systemctl restart nginx
