#!/usr/bin/env bash
# Install HAProxy
sudo apt update
sudo apt install haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
# HAProxy configuration
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server [190865]-web-01 [web-01-54.175.1.126]:80 check
    server [190865]-web-02 [web-02-3.83.253.4]:80 check
EOF

sudo systemctl restart haproxy

