#!/usr/bin/env bash
# Initialize a counter
# On 9th iteration dispaly hi before Best school

count=0


while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo -n "Hi"
  fi
    echo "Best School"
    ((count++))
done
