#!/usr/bin/env bash
#Dispalys numbers from 1-20 in addition tp
#  "bad luck from China for the fourth iteration"
#  "bad luck from Japan for the 9th iteration"
#  "bad luck from Italy for the 17th iteration"

count=1

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
	    "4") echo "bad luck from China";;
	    "9") echo "bad luck from Japan";;
	    "17") echo "bad luck from Italy";;
    esac
  ((count++))
done

