#!/usr/bin/env bash
# Initialize variables for hours and minutes

hour=0
minute=1


while [ "$hour" -le 12 ]
do
    echo "$Hour:$hour"
    while [ $minute -le 59]
    do
	    echo "$minute"
	    ((minute++))
    done
  # Reset the minute and increment the hour
  ((hour++))
done
